"""Exercise actual autogeneration and application against disposable PostgreSQL."""
import os
import shutil
import subprocess
import sys

from conftest import BACKEND, disposable_database, migrate


def test_current_initial_upgrade_downgrade():
    with disposable_database() as name:
        migrate(name, "upgrade", "head")
        migrate(name, "check")
        migrate(name, "downgrade", "base")
        migrate(name, "upgrade", "head")
        migrate(name, "check")


def test_autogenerated_initial_applies_without_manual_edits(tmp_path):
    scripts = tmp_path / "migrations"
    scripts.mkdir()
    (scripts / "versions").mkdir()
    for filename in ("env.py", "script.py.mako"):
        shutil.copy(BACKEND / "monoapi/db/migrations" / filename, scripts / filename)
    config = tmp_path / "alembic.ini"
    config.write_text((BACKEND / "alembic.ini").read_text().replace(
        "script_location = %(here)s/monoapi/db/migrations",
        f"script_location = {scripts}",
    ))
    with disposable_database() as name:
        env = {**os.environ, "PG_DB": name, "ECHO": "false"}

        def run(*args):
            result = subprocess.run(
                [sys.executable, "-m", "alembic", "-c", str(config), *args],
                cwd=BACKEND, env=env, capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stdout + result.stderr

        run("revision", "--autogenerate", "-m", "initial")
        revisions = list((scripts / "versions").glob("*.py"))
        assert len(revisions) == 1
        source = revisions[0].read_text()
        assert "create_constraint=True" not in source
        assert "name='ck_diary_entries_amount_positive'" in source
        # Apply exactly what autogenerate produced, without editing the revision.
        run("upgrade", "head")
        run("check")
        run("downgrade", "base")
        run("upgrade", "head")
        run("check")
