"""initial

Revision ID: e41bb86a40db
Revises: 
Create Date: 2026-09-29 13:51:04.952158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41bb86a40db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('targets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_count', sa.BigInteger(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.CheckConstraint('current_count >= 0', name='ck_targets_current_count_nonnegative'),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='ck_targets_percentage'),
    sa.CheckConstraint('target_count > 0', name='ck_targets_target_count_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_targets_user_id', 'targets', ['user_id'], unique=False)
    op.create_table('users_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_sessions_token'), 'users_sessions', ['token'], unique=True)
    op.create_table('diary_entries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('operation_type', sa.Enum('income', 'expense', 'investment', name='operation_type', native_enum=False), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('Супермаркеты', 'Фастфуд', 'Рестораны', 'Кофейни', 'Доставка еды', 'Общественный транспорт', 'Здоровье и медицина', 'Аптеки', 'Красота и уход', 'Спорт и фитнес', 'Развлечения', 'Кино', 'Книги', 'Образование', 'Одежда и обувь', 'Аксессуары и украшения', 'Электроника и бытовая техника', 'Товары для дома', 'Детские товары', 'Зоотовары', 'Цветы', 'Подарки и сувениры', 'Подписки и цифровые сервисы', 'Благотворительность', 'Прочее', name='operation_category', native_enum=False), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.CheckConstraint("target_id IS NULL OR operation_type = 'investment'", name='ck_diary_entries_target_type'),
    sa.CheckConstraint('amount > 0', name='ck_diary_entries_amount_positive'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_diary_entries_target_id'), 'diary_entries', ['target_id'], unique=False)
    op.create_index('ix_diary_entries_user_id_operation_date', 'diary_entries', ['user_id', 'operation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diary_entries_user_id_operation_date', table_name='diary_entries')
    op.drop_index(op.f('ix_diary_entries_target_id'), table_name='diary_entries')
    op.drop_table('diary_entries')
    op.drop_index(op.f('ix_users_sessions_token'), table_name='users_sessions')
    op.drop_table('users_sessions')
    op.drop_index('ix_targets_user_id', table_name='targets')
    op.drop_table('targets')
    op.drop_table('users')
    # ### end Alembic commands ###
